### ISSUE TITLE
Editor loses focus on Ctrl+k

### ISSUE THREAD

**Issue by s4wny** [Wikunia/brackets-QuickDocsPHP#12]
Currently when you press Ctrl+K the main editor loses focus so you can't continue to write without clicking in the editor or pressing esc. Would be nice if the editor kept the focus.

**Comment by Wikunia** [comment]
Brackets uses `Ctrl-K` for the buildin QuickDocsCSS function where you have the same behaviour. I will check if that's easily possible and user friendly. Thanks for the idea!

**Comment by gcacars** [comment]
How can I switch Ctrl+K in keymap?

**Comment by Wikunia** [comment]
Well Brackets uses the same keyboard shortcut so I think it's not easily possible to change it
